GET http://localhost:3000/api/categorias

###

GET http://localhost:3000/api/categorias/2

###

POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Categoria de prueba"
}

###

PUT http://localhost:3000/api/categorias/16
Content-Type: application/json

{
    "categoriaid": 17,
    "nombre": "Categoria de prueba editada"
}

###

DELETE http://localhost:3000/api/categorias/2